- name: Update apt cache and upgrade packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install Midnight Commander
  apt:
    name: mc
    state: present

- name: Ensure user 'pi' has authorized SSH key
  authorized_key:
    user: pi
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"