- name: Bootstrap Raspberry Pi for k3s
  hosts: localhost
  roles:
    - role: helm     # Install Helm for all users
      become: yes
    - role: portainer # Install portainer (via Helm) inside Kubernetes k3s
      become: no
    - role: k9s      # Install k9s for all users
      become: yes
 
