- name: Install dependencies
  apt:
    name: curl
    state: present

- name: Install required tools
  apt:
    name:
      - iptables
      - iptables-persistent
    state: present

- name: Install k3s
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" bash -
  args:
    creates: /usr/local/bin/k3s

- name: Ensure .kube directory exists for original user
  file:
    path: "/home/{{ ansible_env.SUDO_USER }}/.kube"
    state: directory
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: '0755'

- name: Create symlink to k3s kubeconfig
  file:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "/home/{{ ansible_env.SUDO_USER }}/.kube/config"
    state: link
    force: yes
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"


- name: Let's try the first ever kubernetes command
  ansible.builtin.command: kubectl get nodes
  register: nodes_output

- name: If you see green text in this section that's very good news
  ansible.builtin.debug:
    var: nodes_output.stdout


